/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40021018;
	uint32_t *pPortCModeReg = (uint32_t*)0x40011004;
	uint32_t *pPortCOutReg =  (uint32_t*)0x4001100C;

	//1. enable the clock for GPOIC peripheral in the AHB2ENR (SET the 4th bit position)
	*pClkCtrlReg |= ( 1 << 4);

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th bit positions (CLEAR)
	*pPortCModeReg &= ~( 1 << 20);
	//b. make 24th bit position as 1 (SET)
	*pPortCModeReg |= ( 1 << 24);
	//3.SET 12th bit of the output data register to make I/O pin-12 as HIGH
	*pPortCOutReg |= ( 1 << 13);


}
